second attempt

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,56 +5,51 @@ on:
     types: [created]
 
 jobs:
-  check-migration-changes:
+  valid-tag:
+    name: Validate tag format
     runs-on: ubuntu-latest
-
     steps:
-      - name: Checkout repository
+      - name: Checkout the repository
         uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-      - name: Set up Git
+      - name: Extract the tag name
+        id: extract_tag
+        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
+
+      - name: Validate the tag format
+        id: validate_semver
         run: |
-          git fetch --tags --prune --unshallow
-
-      - name: Get current release version
-        id: get_current_version
-        run: echo "CURRENT_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
-
-      - name: Get previous release version
-        id: get_previous_version
-        run: |
-          PREVIOUS_VERSION=$(git tag --sort=v:refname | grep -v "$CURRENT_VERSION" | tail -n 1)
-          echo "PREVIOUS_VERSION=$PREVIOUS_VERSION" >> $GITHUB_ENV
-
-      - name: Compare files between versions
-        run: |
-          echo "Comparing changes between $PREVIOUS_VERSION and $CURRENT_VERSION"
-          if [ -z $PREVIOUS_VERSION ]; then
-            echo "No previous version found"
-            exit 0
+          if [[ ! "${{ env.tag }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Tag '${{ env.tag }}' does not conform to SemVer."
+            exit 1
           else
-            CHANGED_FILES=$(git diff --name-only $PREVIOUS_VERSION $CURRENT_VERSION)
-            MIGRATIONS_PATH="migrations"
-            CHANGED_IN_MIGRATIONS=$(echo "$CHANGED_FILES" | grep "migrations/")
-            FORBIDDEN_CHANGES=$(echo "$CHANGED_IN_MIGRATIONS" | grep -v "migrations/$CURRENT_VERSION")
-  
-            if [ -n "$FORBIDDEN_CHANGES" ]; then
-                echo "The following changes are illegal:"
-                echo "$FORBIDDEN_CHANGES"
-                exit 1
-            fi
-            
-            echo "All changes are contained within $MIGRATIONS_PATH/$CURRENT_VERSION."
+            echo "Tag ${{ env.tag }} is a valid tag."
+          fi
+          
+  valid-data-folder:
+    name: Ensure a migration folder exists
+    needs: valid-tag
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the repository
+        uses: actions/checkout@v3
+      - name: Check if a data folder exists for the tag
+        id: check_folder
+        run: |
+          echo "Checking if a folder for ${GITHUB_REF#refs/tags/} exists"
+          if [ ! -d "data/migrations/${GITHUB_REF#refs/tags/}" ]; then
+            echo "Error: No folder exists in /data/migrations matching the tag '${GITHUB_REF#refs/tags/}'."
+            echo "$(pwd)"
+            echo "$(ls -l )"
+            echo "$(ls -l data/migrations/)"
+            exit 1
           fi
 
-      - name: Upload changed files list
-        uses: actions/upload-artifact@v3
-        with:
-          name: changed-files
-          path: changed_files.txt
-
-  build:
-    needs: check-migration-changes
+  compiled-artifacts:
+    name: Build backend and frontend artifacts
+    needs: valid-data-folder
     runs-on: ubuntu-latest
     permissions:
       contents: write
@@ -135,10 +130,10 @@ jobs:
         asset_content_type: application/zip
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        
 
-  generate-tags-file:
-    needs: build
+  generated-tags-file:
+    name: Update .meta folder
+    needs: compiled-artifacts
     runs-on: ubuntu-latest
     permissions:
       contents: write  # Grant write permissions for this job to modify the repository
